# Generated by Django 3.0.3 on 2020-05-21 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credits',
            new_name='Credit',
        ),
        migrations.AlterModelOptions(
            name='credit',
            options={'verbose_name': 'Graduation Credit', 'verbose_name_plural': 'Graduation Credits'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Educational Institution', 'verbose_name_plural': 'Educational Institutions'},
        ),
    ]
