# Generated by Django 3.0.3 on 2020-05-21 23:17

import address.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
        ('Education', '0002_auto_20200521_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='class_name',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('next_year_full_tuition', models.DecimalField(decimal_places=2, max_digits=7)),
                ('headmaster', models.CharField(max_length=250)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('fax_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('director_of_admissions', models.CharField(max_length=250)),
                ('application_received', models.BooleanField()),
                ('teacher_recommendations_requested', models.BooleanField()),
                ('application_submitted', models.BooleanField()),
                ('teacher_recommendations_submitted', models.BooleanField()),
                ('financial_aid_requested', models.BooleanField()),
                ('financial_aid_awarded', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField(max_length=10000, null=True)),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
            options={
                'verbose_name': 'Educational Institution',
                'verbose_name_plural': 'Educational Institutions',
            },
        ),
        migrations.AlterField(
            model_name='credit',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Education.Institution'),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
