# Generated by Django 3.0.3 on 2020-05-22 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0003_auto_20200521_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='toured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='credit',
            name='school',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Education.Institution'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='subject',
            field=models.CharField(blank=True, choices=[('ECA.', 'Extracurricular Activity'), ('FART', 'Fine Arts'), ('L.A.', 'Language Arts'), ('MATH', 'Mathematics'), ('O.E.', 'Outdoor Education'), ('P.E.', 'Physical Education'), ('SCI.', 'Science'), ('S.S.', 'Social Studies'), ('TECH', 'Technology'), ('W.L.', 'World Languages')], max_length=4),
        ),
        migrations.AlterField(
            model_name='institution',
            name='application_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='institution',
            name='application_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='institution',
            name='director_of_admissions',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='institution',
            name='financial_aid_awarded',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='institution',
            name='financial_aid_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='institution',
            name='teacher_recommendations_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='institution',
            name='teacher_recommendations_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
