# Generated by Django 3.0.3 on 2020-05-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0004_auto_20200521_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='director_of_admissions',
            new_name='admissions_director',
        ),
        migrations.AddField(
            model_name='institution',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
