# Generated by Django 3.0.5 on 2020-06-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0005_auto_20200522_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['school', 'grade_level', 'subject'], 'verbose_name': 'Graduation Credit', 'verbose_name_plural': 'Graduation Credits'},
        ),
        migrations.AlterField(
            model_name='credit',
            name='grade_level',
            field=models.CharField(choices=[('6th Grade', '6th Grade'), ('7th Grade', '7th Grade'), ('8th Grade', '8th Grade'), ('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate', 'Graduate School')], max_length=9),
        ),
        migrations.AlterField(
            model_name='credit',
            name='required_exam',
            field=models.CharField(blank=True, choices=[('AP', 'Advanced Placement'), ('CLEP', 'College Level Examination Program')], max_length=4),
        ),
        migrations.AlterField(
            model_name='credit',
            name='subject',
            field=models.CharField(blank=True, choices=[('Extracurricular', 'Extracurricular Activity'), ('Fine Arts', 'Fine Arts'), ('Language Arts', 'Language Arts'), ('Mathematics', 'Mathematics'), ('Outdoor Education', 'Outdoor Education'), ('Physical Education', 'Physical Education'), ('Science', 'Science'), ('Social Studies', 'Social Studies'), ('Technology', 'Technology'), ('World Languages', 'World Languages')], max_length=18),
        ),
        migrations.AlterField(
            model_name='institution',
            name='financial_aid_awarded',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
