# Generated by Django 3.0.5 on 2020-06-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0007_auto_20200604_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
