# Generated by Django 3.0.5 on 2020-06-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0009_auto_20200604_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='course_weighted_grade_point_average',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Weighted Grade Point Average for Course'),
        ),
        migrations.AddField(
            model_name='credit',
            name='letter_grade',
            field=models.CharField(blank=True, max_length=2, verbose_name='Letter Grade'),
        ),
        migrations.AddField(
            model_name='credit',
            name='raw_score_grade',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Course Grade Percentage'),
        ),
    ]
