# Generated by Django 3.0.5 on 2020-06-26 05:42

import address.models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('address', '0002_auto_20160213_1726'),
        ('Education', '0012_auto_20200626_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='course_weighted_grade_point_average',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3,
                                      verbose_name='Weighted Grade Point Average (GPA) for <django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='letter_grade',
            field=models.CharField(blank=True, max_length=2,
                                   verbose_name='Letter Grade in <django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='raw_score_grade',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5,
                                      verbose_name='Grade Percentage in <django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='school',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Education.Institution',
                                    verbose_name='Name of the School'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address',
                                              verbose_name="<django.db.models.fields.CharField>'s Address"),
        ),
        migrations.AlterField(
            model_name='institution',
            name='admissions_director',
            field=models.CharField(blank=True, max_length=250,
                                   verbose_name="Name of <django.db.models.fields.CharField>'s Admissions Director"),
        ),
        migrations.AlterField(
            model_name='institution',
            name='headmaster',
            field=models.CharField(max_length=250,
                                   verbose_name="Name of <django.db.models.fields.CharField>'s Head of School"),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name of the School'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='email_address_of_instructor',
            field=models.EmailField(blank=True, max_length=254,
                                    verbose_name="<django.db.models.fields.CharField><django.db.models.fields.CharField>'s Email Address"),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='phone_number_of_instructor',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None,
                                                                 verbose_name="<django.db.models.fields.CharField><django.db.models.fields.CharField>'s Telephone Number"),
        ),
    ]
