# Generated by Django 3.0.5 on 2020-06-27 21:18

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0013_auto_20200626_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='next_year_full_tuition_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CAN', 'Canadian Dollars'), ('EUR', 'Euros'), ('USD', 'US Dollars')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='institution',
            name='next_year_full_tuition',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=7),
        ),
    ]
