# Generated by Django 3.0.5 on 2020-06-28 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0014_auto_20200627_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['school', 'grade_level', 'subject', 'required_exam', 'name'], 'verbose_name': 'Graduation Credit', 'verbose_name_plural': 'Graduation Credits'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name'], 'verbose_name': 'Educational Institution', 'verbose_name_plural': 'Educational Institutions'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Teaching Instructor', 'verbose_name_plural': 'Teaching Instructors'},
        ),
    ]
