# Generated by Django 3.0.5 on 2020-06-29 02:41

import address.models
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
        ('Education', '0015_auto_20200627_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='financial_aid_awarded_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CAN', 'Canadian Dollars'), ('EUR', 'Euros'), ('USD', 'US Dollars')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='credit',
            name='course_weighted_grade_point_average',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, verbose_name='Weighted Grade Point Average (GPA)'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='letter_grade',
            field=models.CharField(blank=True, max_length=2, verbose_name='Letter Grade'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='raw_score_grade',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Raw Class Grade Percentage'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='school',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Education.Institution', verbose_name='Name of Institution'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address', verbose_name="Institution's Address"),
        ),
        migrations.AlterField(
            model_name='institution',
            name='admissions_director',
            field=models.CharField(blank=True, max_length=250, verbose_name="Admissions Director's Name"),
        ),
        migrations.AlterField(
            model_name='institution',
            name='financial_aid_awarded',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='USD', max_digits=7),
        ),
        migrations.AlterField(
            model_name='institution',
            name='headmaster',
            field=models.CharField(max_length=250, verbose_name="Head of School's Name"),
        ),
        migrations.AlterField(
            model_name='institution',
            name='next_year_full_tuition',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='USD', max_digits=7),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='email_address_of_instructor',
            field=models.EmailField(blank=True, max_length=254, verbose_name="Instructor's Email Address"),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='phone_number_of_instructor',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name="Instructor's Telephone Number"),
        ),
    ]
