# Generated by Django 3.0.5 on 2020-06-27 21:18

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='average_salary_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CAN', 'Canadian Dollars'), ('EUR', 'Euros'), ('USD', 'US Dollars')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='career',
            name='average_salary',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='USD', max_digits=6),
        ),
    ]
