# Generated by Django 3.0.5 on 2020-06-28 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_auto_20200627_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['required_education', 'average_salary', 'profession']},
        ),
    ]
