# Generated by Django 3.1.5 on 2021-02-03 00:00

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theanalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='duration',
            field=models.CharField(blank=True, choices=[('1-month', 'Occurs on a Monthly basis'), ('2-months', 'Occurs on a Bi-Monthly basis'), ('3-months', 'Occurs on a Quarterly basis'), ('4-months', 'Occurs on a Annual Trimester basis'), ('5-months', 'Occurs on a 5-Month duration period'), ('6-months', 'Occurs on a Semi-Annual basis'), ('7-months', 'Occurs on a 7-Month duration period'), ('8-months', 'Occurs on a Bi-Trimester basis'), ('9-months', 'Occurs on a Gestational term basis'), ('10-months', 'Occurs on a 10-Month duration period'), ('11-months', 'Occurs on an 11-Month duration period'), ('12-months', 'Occurs on an Annual basis')], default='12-months', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='pay',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, default_currency='USD', max_digits=6, null=True),
        ),
    ]
