# Generated by Django 3.1.5 on 2021-02-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theanalyzer', '0002_auto_20210202_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='duration',
            field=models.CharField(blank=True, choices=[('1-month', 'occurring on a Monthly basis'), ('2-months', 'occurring on a Bi-Monthly basis'), ('3-months', 'occurring on a Quarterly basis'), ('4-months', 'occurring on a Annual Trimester basis'), ('5-months', 'occurring on a 5-Month duration period'), ('6-months', 'occurring on a Semi-Annual basis'), ('7-months', 'occurring on a 7-Month duration period'), ('8-months', 'occurring on a Bi-Trimester basis'), ('9-months', 'occurring on a Gestational term basis'), ('10-months', 'occurring on a 10-Month duration period'), ('11-months', 'occurring on an 11-Month duration period'), ('12-months', 'occurring on an Annual basis')], default='12-months', max_length=40, null=True),
        ),
    ]
