# Generated by Django 3.1.5 on 2021-02-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theanalyzer', '0003_auto_20210202_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='classification',
            field=models.CharField(blank=True, choices=[('Employee Wages (W-2)', 'Employee Wages (W-2)'), ('Contract', 'Contract'), ('Contract-to-Hire', 'Contract-to-Hire'), ('Corp-to-Corp', 'Corp-to-Corp')], default='Employee Wages (W-2)', max_length=20, null=True),
        ),
    ]
