# Generated by Django 3.1.5 on 2021-03-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theanalyzer', '0005_position_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['pay']},
        ),
        migrations.AlterModelOptions(
            name='recruiter',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='position',
            name='benefit',
        ),
        migrations.AddField(
            model_name='position',
            name='benefit',
            field=models.ManyToManyField(blank=True, null=True, to='theanalyzer.Benefit'),
        ),
    ]
