# Generated by Django 3.1.5 on 2021-03-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theanalyzer', '0006_auto_20210307_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='benefit',
            field=models.ManyToManyField(blank=True, to='theanalyzer.Benefit'),
        ),
    ]
