# Generated by Django 3.1.5 on 2021-03-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theanalyzer', '0007_auto_20210309_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='position',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='interviewed',
            field=models.BooleanField(default=False),
        ),
    ]
