# Generated by Django 3.1.7 on 2021-03-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theanalyzer', '0009_auto_20210309_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
